/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageErrorHandler: typeof import('./src/components/MessageErrorHandler.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
  }
}
